workflows:
  react_native_build:
    name: React Native Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS
        script: |
          npx react-native run-ios 
      - name: Build iOS signed      
        script: xcode-project build-ipa --project "ios/test3reactnative.xcodeproj" --scheme "xcschemes"
