workflows:
  react_native_build:
    name: React Native Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS
        script: |
          npx react-native run-ios 
      - name: Build iOS signed      
        script: xcodebuild -workspace test3reactnative
 -scheme YourScheme -configuration Release -archivePath build/test3reactnative.xcarchive archive
          xcodebuild -exportArchive -archivePath build/test3reactnative.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build
