workflows:
  react_native_build:
    name: React Native Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build Android
        script: |
          npx react-native run-android
      - name: Build iOS
        script: |
          npx react-native run-ios --configuration Release --device
