workflows:
  react_native_build:
    name: React Native Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS
        script: |
          npx react-native run-ios 
      - name: Build iOS unsigned      # this will generate .app file
        script: |
         xcodebuild build -project "test3reactnative.xcodeproj" \
         -scheme "xcschemes" \
          CODE_SIGN_INDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO    

       - name: Build iOS signed      # this will generate .ipa file
          script: xcode-project build-ipa --project "MyXcodeProject.xcodeproj" --scheme "xcschemes"
