workflows:
  react_native_build:
    name: React Native Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS
        script: |
          npx react-native run-ios 
      - name: Build iOS IPA
        script: |
          npx react-native run-ios --configuration Release --device
          xcodebuild -workspace test3reactnative.xcworkspace -scheme test3reactnative -configuration Release -archivePath build/test3reactnative.xcarchive archive
          xcodebuild -exportArchive -archivePath build/test3reactnative.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist
