workflows:
  react_native_build:
    name: React Native Build
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install && cd ..
      - name: Build iOS
        script: |
          npx react-native run-ios 
      - name: Build iOS IPA
        script: |
         xcodebuild -workspace ios/test3reactnative.xcodeproj -scheme test3reactnative -archivePath build/test3reactnative.xcarchive archive
          xcodebuild -exportArchive -archivePath build/test3reactnative.xcarchive -exportPath build -exportOptionsPlist path/to/your/ExportOptions.plist
