workflows:
  build:
    name: Build IPA
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
    
      - name: Download IPA
        script: |
          curl -o test3reactnative.ipa https://api.codemagic.io/artifacts/download/66412d7e304fb696e70f7e58/test3reactnative.ipa?branch=master
